- Caio:
	- criar e compartilhar projeto no git	ok
	- limpar e ajustar o código				ok
	- ajustar dropdown 'sobre nos'			ok
	- ajustar button 'responsivo'			ok
	- fazer imagens das paginas no canva	ok
	- desenvolver footer (bootstrap)		ok
	- comentar codigo já desenvolvido		ok
	- desenv template -> 'como chegar'

- Jonas:
	- pesquisar ideias para o desenvolvimento das páginas
